# 0. Colors (must be first — general.conf depends on these variables)
source = ~/.config/hypr/hyprland/colors.conf
# 1. Monitors
source = ~/.config/hypr/hyprland/monitors.conf
# 2. Appearance & General Settings
source = ~/.config/hypr/hyprland/general.conf
# 3. Executables (Autostart)
source = ~/.config/hypr/hyprland/execs.conf
# 4. Rules (Window & Layer)
source = ~/.config/hypr/hyprland/rules.conf
# 5. Keybindings
source = ~/.config/hypr/hyprland/keybinds.conf
